#!/bin/sh
#
#  Copyright (C) 2017-2018 Savoir-Faire Linux Inc.
#
#  Authors:
#      Gaël PORTAY <gael.portay@savoirfairelinux.com>
#
# SPDX-License-Identifier: LGPL-2.1-or-later
#

set -e

PATH=/usr/bin:/usr/sbin:/bin:sbin
export PATH

mount -t proc proc /proc
mount -t sysfs sysfs /sys

if ! grep -q '^devtmpfs ' /proc/mounts && \
   ! mount -t devtmpfs devtmpfs /dev; then
	cat <<EOF >&2
rcS: Warning: kernel has not been compiled with devtmpfs filesystem!
     Check for CONFIG_DEVTMPFS and
               CONFIG_DEVTMPFS_MOUNT.
EOF
fi
